/**
 * Builds src/data/dictionary.ru.ts — frequent Russian words for talk-mode autocomplete
 * (docs/TRANSLATOR_SPEC.md §4.1) — from the FrequencyWords list (Hermit Dave, OpenSubtitles 2018;
 * code MIT, word lists CC BY-SA 4.0): https://github.com/hermitdave/FrequencyWords
 *
 * Download ru_50k.txt into scripts/data/raw/dictionary/ (gitignored), then: npm run build:dictionary
 */
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { WORDS } from "../src/data/words";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const SOURCE = path.join(ROOT, "scripts/data/raw/dictionary/ru_50k.txt");
const TARGET = path.join(ROOT, "src/data/dictionary.ru.ts");
const SIZE = 4000;
const PER_LINE = 16;

// Subtitles are full of swearing: never suggest it. Roots that are safe as substrings…
const OBSCENE_ANYWHERE = /(хуй|хуе|хуё|хуя|пизд|мудак|мудил|пидор|пидар|пидр|гандон|залуп|шлюх|дерьм|говн|жоп|ублюд|дроч)/;
// …and roots that only count at the start of a word («корабля», «страх», «хлебать» are fine).
const OBSCENE_START = /^((за|вы|на|по|у|от|отъ|съ|раз|разъ|про|долбо)?[её]б|бля|сук[аио]|сучк|сучар|трах|мраз|сра[тл]|ссан)/;

const isWord = (w: string) => /^[а-яё]{2,}$/.test(w) && !OBSCENE_ANYWHERE.test(w) && !OBSCENE_START.test(w);

const frequent = readFileSync(SOURCE, "utf8")
  .split(/\r?\n/)
  .map((line) => line.split(" ")[0]?.trim().toLocaleLowerCase("ru-RU") ?? "")
  .filter(isWord)
  .slice(0, SIZE)
  .map((w) => w.toLocaleUpperCase("ru-RU"));

// Words of the Тренажёр are always there, even when rare in subtitles.
const words = [...new Set([...frequent, ...WORDS])];

const lines: string[] = [];
for (let i = 0; i < words.length; i += PER_LINE) lines.push(`  ${words.slice(i, i + PER_LINE).join(" ")}`);

writeFileSync(
  TARGET,
  `// GENERATED by scripts/build-dictionary.ts — do not edit by hand.
// ${words.length} frequent Russian words, most frequent first, for talk-mode autocomplete.
// Source: FrequencyWords by Hermit Dave (OpenSubtitles 2018), CC BY-SA 4.0 —
// https://github.com/hermitdave/FrequencyWords. Obscene words are filtered out; words.ts is appended.

const TEXT = \`
${lines.join("\n")}
\`;

export const DICTIONARY: readonly string[] = TEXT.split(/\\s+/).filter(Boolean);
`,
  "utf8",
);

console.log(`dictionary.ru.ts: ${words.length} words (${frequent.length} frequent + words.ts)`);
