// AUTO-GENERATED by scripts/build-letters.ts (npm run build:letters) — do not edit by hand.
// Team decisions go to letters.overrides.ts: they survive a rebuild.
// Rules come from data statistics only (a rule needs ≥ 80% of the samples) and are NOT verified
// against the official table yet (CLAUDE.md §8.1).
import type { LetterBuildInfo } from "../recognition/letters/build/info";
import type { LetterSpec } from "../recognition/letters/spec";

export const GENERATED_LETTERS: readonly LetterSpec[] = [
  // А: 78 samples (kaggle 58, rsl 20), 23 signers, 3 Left/Right fixed, kNN accuracy 96% (leave-one-signer-out)
  //   thumb  straight 62% / half 36% / bent 3%, median 155° → free
  //   index  straight 0% / half 4% / bent 96%, median 82° → rule: bent
  //   middle straight 0% / half 1% / bent 99%, median 76.8° → rule: bent
  //   ring   straight 0% / half 1% / bent 99%, median 73.8° → rule: bent
  //   pinky  straight 0% / half 1% / bent 99%, median 74.3° → rule: bent
  //   tips touch: index-middle 67%, middle-ring 65%, middle-pinky 53%, ring-pinky 80%
  //   palm: camera 55% / side 44% / away 1% (no rule — photos are shot from any side)
  //   thumb: acrossPalm 28% / side 44% / up 28% (no rule)
  {
    letter: "А",
    verified: false,
    fingers: {
      index: { state: "bent", hintCode: "finger.bend.index" },
      middle: { state: "bent", hintCode: "finger.bend.middle" },
      ring: { state: "bent", hintCode: "finger.bend.ring" },
      pinky: { state: "bent", hintCode: "finger.bend.pinky" },
    },
    reference: "references/А.json",
  },
  // Б: 77 samples (kaggle 57, rsl 20), 20 signers, 111 Left/Right fixed, kNN accuracy 77% (leave-one-signer-out)
  //   thumb  straight 39% / half 48% / bent 13%, median 143° → free
  //   index  straight 30% / half 65% / bent 5%, median 153° → free
  //   middle straight 5% / half 66% / bent 29%, median 107.8° → free
  //   ring   straight 1% / half 12% / bent 87%, median 84.4° → rule: bent
  //   pinky  straight 0% / half 20% / bent 81%, median 85.2° → rule: bent
  //   tips touch: ring-pinky 82%
  //   not a rule (both fingers bent): ring-pinky
  //   palm: camera 18% / side 65% / away 17% (no rule — photos are shot from any side)
  //   thumb: acrossPalm 52% / side 48% / up 0% (no rule)
  {
    letter: "Б",
    verified: false,
    fingers: {
      ring: { state: "bent", hintCode: "finger.bend.ring" },
      pinky: { state: "bent", hintCode: "finger.bend.pinky" },
    },
    reference: "references/Б.json",
    confusedWith: ["К", "Я"],
  },
  // В: 75 samples (kaggle 55, rsl 20), 20 signers, 25 Left/Right fixed, kNN accuracy 100% (leave-one-signer-out)
  //   thumb  straight 100% / half 0% / bent 0%, median 165.6° → rule: straight
  //   index  straight 73% / half 27% / bent 0%, median 161.8° → free
  //   middle straight 100% / half 0% / bent 0%, median 170.3° → rule: straight
  //   ring   straight 100% / half 0% / bent 0%, median 170.4° → rule: straight
  //   pinky  straight 85% / half 15% / bent 0%, median 162.7° → rule: straight
  //   tips touch: index-middle 97%, middle-ring 96%
  //   palm: camera 100% / side 0% / away 0% (no rule — photos are shot from any side)
  //   thumb: acrossPalm 0% / side 99% / up 1% (no rule)
  {
    letter: "В",
    verified: false,
    fingers: {
      thumb: { state: "straight", hintCode: "finger.straighten.thumb" },
      middle: { state: "straight", hintCode: "finger.straighten.middle" },
      ring: { state: "straight", hintCode: "finger.straighten.ring" },
      pinky: { state: "straight", hintCode: "finger.straighten.pinky" },
    },
    extra: [
      { type: "tipsTouch", a: "index", b: "middle", hintCode: "tips.touch.index-middle" },
      { type: "tipsTouch", a: "middle", b: "ring", hintCode: "tips.touch.middle-ring" },
    ],
    reference: "references/В.json",
    confusedWith: ["Т", "Ё"],
  },
  // Г: 70 samples (kaggle 50, rsl 20), 14 signers, 78 Left/Right fixed, kNN accuracy 94% (leave-one-signer-out)
  //   thumb  straight 94% / half 6% / bent 0%, median 165.8° → rule: straight
  //   index  straight 0% / half 97% / bent 3%, median 140° → rule: half
  //   middle straight 0% / half 1% / bent 99%, median 44.7° → rule: bent
  //   ring   straight 0% / half 1% / bent 99%, median 48° → rule: bent
  //   pinky  straight 0% / half 1% / bent 99%, median 43.7° → rule: bent
  //   tips touch: ring-pinky 59%
  //   palm: camera 83% / side 17% / away 0% (no rule — photos are shot from any side)
  //   thumb: acrossPalm 0% / side 81% / up 19% (no rule)
  {
    letter: "Г",
    verified: false,
    fingers: {
      thumb: { state: "straight", hintCode: "finger.straighten.thumb" },
      index: { state: "half", hintCode: "finger.round.index" },
      middle: { state: "bent", hintCode: "finger.bend.middle" },
      ring: { state: "bent", hintCode: "finger.bend.ring" },
      pinky: { state: "bent", hintCode: "finger.bend.pinky" },
    },
    reference: "references/Г.json",
  },
  // Д: 20 samples (rsl 20), 1 signers, 22 Left/Right fixed, kNN accuracy 60% (leave-one-out, 1 signer)
  //   thumb  straight 55% / half 45% / bent 0%, median 152.5° → free
  //   index  straight 50% / half 50% / bent 0%, median 161° → free
  //   middle straight 35% / half 50% / bent 15%, median 151.9° → free
  //   ring   straight 0% / half 45% / bent 55%, median 91.9° → free
  //   pinky  straight 0% / half 60% / bent 40%, median 109.4° → free
  //   palm: camera 55% / side 45% / away 0% (no rule — photos are shot from any side)
  //   thumb: acrossPalm 45% / side 40% / up 15% (no rule)
  { letter: "Д", verified: false, fingers: {}, reference: "references/Д.json", confusedWith: ["Я", "Э", "З"] },
  // Е: 48 samples (kaggle 48), 10 signers, 2 Left/Right fixed, kNN accuracy 94% (leave-one-signer-out)
  //   thumb  straight 88% / half 13% / bent 0%, median 159.4° → rule: straight
  //   index  straight 0% / half 71% / bent 29%, median 108.4° → free
  //   middle straight 0% / half 65% / bent 35%, median 104.7° → free
  //   ring   straight 0% / half 58% / bent 42%, median 104.7° → free
  //   pinky  straight 0% / half 88% / bent 13%, median 115.4° → rule: half
  //   tips touch: index-middle 90%, index-ring 83%, index-pinky 54%, middle-ring 98%, middle-pinky 85%, ring-pinky 96%
  //   palm: camera 25% / side 71% / away 4% (no rule — photos are shot from any side)
  //   thumb: acrossPalm 52% / side 46% / up 2% (no rule)
  {
    letter: "Е",
    verified: false,
    fingers: {
      thumb: { state: "straight", hintCode: "finger.straighten.thumb" },
      pinky: { state: "half", hintCode: "finger.round.pinky" },
    },
    extra: [
      { type: "tipsTouch", a: "index", b: "middle", hintCode: "tips.touch.index-middle" },
      { type: "tipsTouch", a: "index", b: "ring", hintCode: "tips.touch.index-ring" },
      { type: "tipsTouch", a: "middle", b: "ring", hintCode: "tips.touch.middle-ring" },
      { type: "tipsTouch", a: "middle", b: "pinky", hintCode: "tips.touch.middle-pinky" },
      { type: "tipsTouch", a: "ring", b: "pinky", hintCode: "tips.touch.ring-pinky" },
    ],
    reference: "references/Е.json",
    confusedWith: ["Ё"],
  },
  // Ё: 20 samples (rsl 20), 1 signers, 6 Left/Right fixed, kNN accuracy 75% (leave-one-out, 1 signer)
  //   thumb  straight 100% / half 0% / bent 0%, median 166.7° → rule: straight
  //   index  straight 5% / half 95% / bent 0%, median 121.6° → rule: half
  //   middle straight 0% / half 100% / bent 0%, median 114.3° → rule: half
  //   ring   straight 5% / half 90% / bent 5%, median 113.4° → rule: half
  //   pinky  straight 0% / half 100% / bent 0%, median 111.2° → rule: half
  //   tips touch: index-middle 85%, middle-ring 80%, ring-pinky 100%
  //   palm: camera 15% / side 80% / away 5% (no rule — photos are shot from any side)
  //   thumb: acrossPalm 0% / side 100% / up 0% (no rule)
  {
    letter: "Ё",
    verified: false,
    fingers: {
      thumb: { state: "straight", hintCode: "finger.straighten.thumb" },
      index: { state: "half", hintCode: "finger.round.index" },
      middle: { state: "half", hintCode: "finger.round.middle" },
      ring: { state: "half", hintCode: "finger.round.ring" },
      pinky: { state: "half", hintCode: "finger.round.pinky" },
    },
    extra: [
      { type: "tipsTouch", a: "index", b: "middle", hintCode: "tips.touch.index-middle" },
      { type: "tipsTouch", a: "middle", b: "ring", hintCode: "tips.touch.middle-ring" },
      { type: "tipsTouch", a: "ring", b: "pinky", hintCode: "tips.touch.ring-pinky" },
    ],
    reference: "references/Ё.json",
    confusedWith: ["Е", "Ж", "В"],
  },
  // Ж: 71 samples (kaggle 51, rsl 20), 21 signers, 80 Left/Right fixed, kNN accuracy 79% (leave-one-signer-out)
  //   thumb  straight 94% / half 4% / bent 1%, median 162.9° → rule: straight
  //   index  straight 1% / half 56% / bent 42%, median 101.9° → free
  //   middle straight 1% / half 37% / bent 62%, median 96° → free
  //   ring   straight 3% / half 32% / bent 65%, median 96.4° → free
  //   pinky  straight 3% / half 41% / bent 56%, median 98° → free
  //   tips touch: index-middle 82%, index-ring 58%, middle-ring 76%, ring-pinky 86%
  //   palm: camera 18% / side 38% / away 44% (no rule — photos are shot from any side)
  //   thumb: acrossPalm 30% / side 68% / up 3% (no rule)
  {
    letter: "Ж",
    verified: false,
    fingers: { thumb: { state: "straight", hintCode: "finger.straighten.thumb" } },
    extra: [
      { type: "tipsTouch", a: "index", b: "middle", hintCode: "tips.touch.index-middle" },
      { type: "tipsTouch", a: "ring", b: "pinky", hintCode: "tips.touch.ring-pinky" },
    ],
    reference: "references/Ж.json",
    confusedWith: ["Ё", "С"],
  },
  // З: 20 samples (rsl 20), 1 signers, 0 Left/Right fixed, kNN accuracy 100% (leave-one-out, 1 signer)
  //   thumb  straight 5% / half 95% / bent 0%, median 141.6° → rule: half
  //   index  straight 95% / half 5% / bent 0%, median 168.7° → rule: straight
  //   middle straight 15% / half 40% / bent 45%, median 107.3° → free
  //   ring   straight 0% / half 10% / bent 90%, median 87.4° → rule: bent
  //   pinky  straight 0% / half 5% / bent 95%, median 88.4° → rule: bent
  //   tips touch: ring-pinky 95%
  //   not a rule (both fingers bent): ring-pinky
  //   palm: camera 100% / side 0% / away 0% (no rule — photos are shot from any side)
  //   thumb: acrossPalm 100% / side 0% / up 0% (no rule)
  {
    letter: "З",
    verified: false,
    fingers: {
      thumb: { state: "half", hintCode: "finger.round.thumb" },
      index: { state: "straight", hintCode: "finger.straighten.index" },
      ring: { state: "bent", hintCode: "finger.bend.ring" },
      pinky: { state: "bent", hintCode: "finger.bend.pinky" },
    },
    reference: "references/З.json",
    confusedWith: ["Д"],
  },
  // И: 56 samples (kaggle 56), 16 signers, 0 Left/Right fixed, kNN accuracy 86% (leave-one-signer-out)
  //   thumb  straight 11% / half 54% / bent 36%, median 126.5° → free
  //   index  straight 5% / half 13% / bent 82%, median 69.3° → rule: bent
  //   middle straight 0% / half 9% / bent 91%, median 73.3° → rule: bent
  //   ring   straight 11% / half 68% / bent 21%, median 153.6° → free
  //   pinky  straight 79% / half 20% / bent 2%, median 170° → free
  //   tips touch: index-middle 52%
  //   palm: camera 100% / side 0% / away 0% (no rule — photos are shot from any side)
  //   thumb: acrossPalm 5% / side 95% / up 0% (no rule)
  {
    letter: "И",
    verified: false,
    fingers: {
      index: { state: "bent", hintCode: "finger.bend.index" },
      middle: { state: "bent", hintCode: "finger.bend.middle" },
    },
    reference: "references/И.json",
    confusedWith: ["У"],
  },
  // Й: 20 samples (rsl 20), 1 signers, 0 Left/Right fixed, kNN accuracy 100% (leave-one-out, 1 signer)
  //   thumb  straight 20% / half 80% / bent 0%, median 147.2° → rule: half
  //   index  straight 0% / half 0% / bent 100%, median 49° → rule: bent
  //   middle straight 0% / half 0% / bent 100%, median 49.8° → rule: bent
  //   ring   straight 100% / half 0% / bent 0%, median 166.5° → rule: straight
  //   pinky  straight 100% / half 0% / bent 0%, median 163.1° → rule: straight
  //   tips touch: thumb-middle 90%, index-middle 90%, ring-pinky 50%
  //   not a rule (both fingers bent): index-middle
  //   palm: camera 100% / side 0% / away 0% (no rule — photos are shot from any side)
  //   thumb: acrossPalm 85% / side 15% / up 0% (no rule)
  {
    letter: "Й",
    verified: false,
    fingers: {
      thumb: { state: "half", hintCode: "finger.round.thumb" },
      index: { state: "bent", hintCode: "finger.bend.index" },
      middle: { state: "bent", hintCode: "finger.bend.middle" },
      ring: { state: "straight", hintCode: "finger.straighten.ring" },
      pinky: { state: "straight", hintCode: "finger.straighten.pinky" },
    },
    extra: [{ type: "tipsTouch", a: "thumb", b: "middle", hintCode: "tips.touch.thumb-middle" }],
    reference: "references/Й.json",
  },
  // К: 76 samples (kaggle 56, rsl 20), 17 signers, 86 Left/Right fixed, kNN accuracy 67% (leave-one-signer-out)
  //   thumb  straight 22% / half 49% / bent 29%, median 133.3° → free
  //   index  straight 58% / half 42% / bent 0%, median 162.2° → free
  //   middle straight 29% / half 66% / bent 5%, median 152.9° → free
  //   ring   straight 1% / half 3% / bent 96%, median 79.3° → rule: bent
  //   pinky  straight 0% / half 7% / bent 93%, median 80.4° → rule: bent
  //   tips touch: ring-pinky 80%
  //   not a rule (both fingers bent): ring-pinky
  //   palm: camera 45% / side 43% / away 12% (no rule — photos are shot from any side)
  //   thumb: acrossPalm 68% / side 32% / up 0% (no rule)
  {
    letter: "К",
    verified: false,
    fingers: {
      ring: { state: "bent", hintCode: "finger.bend.ring" },
      pinky: { state: "bent", hintCode: "finger.bend.pinky" },
    },
    reference: "references/К.json",
    confusedWith: ["Я", "Б", "О"],
  },
  // Л: 75 samples (kaggle 55, rsl 20), 24 signers, 5 Left/Right fixed, kNN accuracy 87% (leave-one-signer-out)
  //   thumb  straight 31% / half 69% / bent 0%, median 146.3° → free
  //   index  straight 44% / half 56% / bent 0%, median 155.8° → free
  //   middle straight 45% / half 55% / bent 0%, median 155.8° → free
  //   ring   straight 0% / half 9% / bent 91%, median 56.5° → rule: bent
  //   pinky  straight 0% / half 16% / bent 84%, median 78.4° → rule: bent
  //   palm: camera 0% / side 15% / away 85% (no rule — photos are shot from any side)
  //   thumb: acrossPalm 65% / side 32% / up 3% (no rule)
  {
    letter: "Л",
    verified: false,
    fingers: {
      ring: { state: "bent", hintCode: "finger.bend.ring" },
      pinky: { state: "bent", hintCode: "finger.bend.pinky" },
    },
    reference: "references/Л.json",
    confusedWith: ["П", "М", "Т"],
  },
  // М: 69 samples (kaggle 49, rsl 20), 20 signers, 1 Left/Right fixed, kNN accuracy 73% (leave-one-signer-out)
  //   thumb  straight 73% / half 28% / bent 0%, median 152.2° → free
  //   index  straight 45% / half 55% / bent 0%, median 156.7° → free
  //   middle straight 46% / half 54% / bent 0%, median 158.8° → free
  //   ring   straight 45% / half 54% / bent 1%, median 156.9° → free
  //   pinky  straight 19% / half 74% / bent 7%, median 135.4° → free
  //   palm: camera 0% / side 13% / away 87% (no rule — photos are shot from any side)
  //   thumb: acrossPalm 17% / side 70% / up 13% (no rule)
  { letter: "М", verified: false, fingers: {}, reference: "references/М.json", confusedWith: ["Ш", "П", "Л"] },
  // Н: 80 samples (kaggle 60, rsl 20), 20 signers, 1 Left/Right fixed, kNN accuracy 99% (leave-one-signer-out)
  //   thumb  straight 1% / half 65% / bent 34%, median 127.5° → free
  //   index  straight 94% / half 6% / bent 0%, median 172.3° → rule: straight
  //   middle straight 98% / half 3% / bent 0%, median 166.9° → rule: straight
  //   ring   straight 1% / half 0% / bent 99%, median 70.7° → rule: bent
  //   pinky  straight 95% / half 5% / bent 0%, median 165.8° → rule: straight
  //   palm: camera 99% / side 1% / away 0% (no rule — photos are shot from any side)
  //   thumb: acrossPalm 94% / side 6% / up 0% (no rule)
  {
    letter: "Н",
    verified: false,
    fingers: {
      index: { state: "straight", hintCode: "finger.straighten.index" },
      middle: { state: "straight", hintCode: "finger.straighten.middle" },
      ring: { state: "bent", hintCode: "finger.bend.ring" },
      pinky: { state: "straight", hintCode: "finger.straighten.pinky" },
    },
    reference: "references/Н.json",
  },
  // О: 80 samples (kaggle 60, rsl 20), 23 signers, 107 Left/Right fixed, kNN accuracy 66% (leave-one-signer-out)
  //   thumb  straight 89% / half 10% / bent 1%, median 160.3° → rule: straight
  //   index  straight 11% / half 85% / bent 4%, median 122° → rule: half
  //   middle straight 24% / half 76% / bent 0%, median 153.4° → free
  //   ring   straight 38% / half 63% / bent 0%, median 155° → free
  //   pinky  straight 35% / half 64% / bent 1%, median 156.2° → free
  //   palm: camera 16% / side 15% / away 69% (no rule — photos are shot from any side)
  //   thumb: acrossPalm 4% / side 91% / up 5% (no rule)
  {
    letter: "О",
    verified: false,
    fingers: {
      thumb: { state: "straight", hintCode: "finger.straighten.thumb" },
      index: { state: "half", hintCode: "finger.round.index" },
    },
    reference: "references/О.json",
    confusedWith: ["С", "Ф", "К"],
  },
  // П: 68 samples (kaggle 48, rsl 20), 19 signers, 33 Left/Right fixed, kNN accuracy 43% (leave-one-signer-out)
  //   thumb  straight 63% / half 37% / bent 0%, median 154.2° → free
  //   index  straight 28% / half 60% / bent 12%, median 128.5° → free
  //   middle straight 16% / half 56% / bent 28%, median 126.1° → free
  //   ring   straight 6% / half 21% / bent 74%, median 72.4° → free
  //   pinky  straight 7% / half 27% / bent 66%, median 87.2° → free
  //   palm: camera 2% / side 59% / away 40% (no rule — photos are shot from any side)
  //   thumb: acrossPalm 27% / side 46% / up 28% (no rule)
  { letter: "П", verified: false, fingers: {}, reference: "references/П.json", confusedWith: ["Л", "Т", "М"] },
  // Р: 74 samples (kaggle 54, rsl 20), 18 signers, 2 Left/Right fixed, kNN accuracy 87% (leave-one-signer-out)
  //   thumb  straight 64% / half 35% / bent 1%, median 154.6° → free
  //   index  straight 74% / half 22% / bent 4%, median 164.2° → free
  //   middle straight 7% / half 38% / bent 55%, median 94.6° → free
  //   ring   straight 72% / half 23% / bent 5%, median 164.5° → free
  //   pinky  straight 84% / half 16% / bent 0%, median 167.2° → rule: straight
  //   palm: camera 89% / side 11% / away 0% (no rule — photos are shot from any side)
  //   thumb: acrossPalm 3% / side 97% / up 0% (no rule)
  {
    letter: "Р",
    verified: false,
    fingers: { pinky: { state: "straight", hintCode: "finger.straighten.pinky" } },
    reference: "references/Р.json",
  },
  // С: 77 samples (kaggle 57, rsl 20), 22 signers, 127 Left/Right fixed, kNN accuracy 74% (leave-one-signer-out)
  //   thumb  straight 90% / half 10% / bent 0%, median 160.1° → rule: straight
  //   index  straight 1% / half 96% / bent 3%, median 136.6° → rule: half
  //   middle straight 0% / half 94% / bent 7%, median 131.4° → rule: half
  //   ring   straight 0% / half 92% / bent 8%, median 131.2° → rule: half
  //   pinky  straight 0% / half 94% / bent 7%, median 141.5° → rule: half
  //   tips touch: index-middle 65%, index-ring 52%, middle-ring 77%, ring-pinky 57%
  //   palm: camera 8% / side 64% / away 29% (no rule — photos are shot from any side)
  //   thumb: acrossPalm 27% / side 70% / up 3% (no rule)
  {
    letter: "С",
    verified: false,
    fingers: {
      thumb: { state: "straight", hintCode: "finger.straighten.thumb" },
      index: { state: "half", hintCode: "finger.round.index" },
      middle: { state: "half", hintCode: "finger.round.middle" },
      ring: { state: "half", hintCode: "finger.round.ring" },
      pinky: { state: "half", hintCode: "finger.round.pinky" },
    },
    reference: "references/С.json",
    confusedWith: ["Х", "О", "Ж"],
  },
  // Т: 71 samples (kaggle 51, rsl 20), 19 signers, 93 Left/Right fixed, kNN accuracy 59% (leave-one-signer-out)
  //   thumb  straight 69% / half 31% / bent 0%, median 153.3° → free
  //   index  straight 14% / half 82% / bent 4%, median 133.1° → rule: half
  //   middle straight 14% / half 80% / bent 6%, median 134.8° → rule: half
  //   ring   straight 14% / half 76% / bent 10%, median 134.1° → free
  //   pinky  straight 9% / half 80% / bent 11%, median 130° → rule: half
  //   palm: camera 37% / side 52% / away 11% (no rule — photos are shot from any side)
  //   thumb: acrossPalm 17% / side 47% / up 37% (no rule)
  {
    letter: "Т",
    verified: false,
    fingers: {
      index: { state: "half", hintCode: "finger.round.index" },
      middle: { state: "half", hintCode: "finger.round.middle" },
      pinky: { state: "half", hintCode: "finger.round.pinky" },
    },
    reference: "references/Т.json",
    confusedWith: ["П", "Ф", "С"],
  },
  // У: 80 samples (kaggle 60, rsl 20), 22 signers, 0 Left/Right fixed, kNN accuracy 96% (leave-one-signer-out)
  //   thumb  straight 96% / half 4% / bent 0%, median 169.6° → rule: straight
  //   index  straight 0% / half 3% / bent 98%, median 60.8° → rule: bent
  //   middle straight 0% / half 3% / bent 98%, median 63.9° → rule: bent
  //   ring   straight 0% / half 0% / bent 100%, median 56.1° → rule: bent
  //   pinky  straight 85% / half 11% / bent 4%, median 167.9° → rule: straight
  //   tips touch: index-middle 78%, middle-ring 74%
  //   palm: camera 100% / side 0% / away 0% (no rule — photos are shot from any side)
  //   thumb: acrossPalm 0% / side 66% / up 34% (no rule)
  {
    letter: "У",
    verified: false,
    fingers: {
      thumb: { state: "straight", hintCode: "finger.straighten.thumb" },
      index: { state: "bent", hintCode: "finger.bend.index" },
      middle: { state: "bent", hintCode: "finger.bend.middle" },
      ring: { state: "bent", hintCode: "finger.bend.ring" },
      pinky: { state: "straight", hintCode: "finger.straighten.pinky" },
    },
    reference: "references/У.json",
    confusedWith: ["И"],
  },
  // Ф: 69 samples (kaggle 49, rsl 20), 19 signers, 63 Left/Right fixed, kNN accuracy 64% (leave-one-signer-out)
  //   thumb  straight 97% / half 3% / bent 0%, median 168.5° → rule: straight
  //   index  straight 6% / half 33% / bent 61%, median 92.5° → free
  //   middle straight 12% / half 23% / bent 65%, median 89.3° → free
  //   ring   straight 10% / half 26% / bent 64%, median 92.4° → free
  //   pinky  straight 12% / half 45% / bent 44%, median 103.5° → free
  //   tips touch: index-middle 71%, middle-ring 74%, ring-pinky 51%
  //   palm: camera 20% / side 67% / away 13% (no rule — photos are shot from any side)
  //   thumb: acrossPalm 7% / side 81% / up 12% (no rule)
  {
    letter: "Ф",
    verified: false,
    fingers: { thumb: { state: "straight", hintCode: "finger.straighten.thumb" } },
    reference: "references/Ф.json",
    confusedWith: ["Т", "О", "Я"],
  },
  // Х: 83 samples (kaggle 63, rsl 20), 23 signers, 94 Left/Right fixed, kNN accuracy 71% (leave-one-signer-out)
  //   thumb  straight 46% / half 48% / bent 6%, median 149° → free
  //   index  straight 0% / half 95% / bent 5%, median 138.9° → rule: half
  //   middle straight 0% / half 1% / bent 99%, median 84.8° → rule: bent
  //   ring   straight 0% / half 0% / bent 100%, median 80° → rule: bent
  //   pinky  straight 1% / half 5% / bent 94%, median 79.7° → rule: bent
  //   tips touch: middle-ring 90%, ring-pinky 92%
  //   not a rule (both fingers bent): middle-ring, ring-pinky
  //   palm: camera 31% / side 59% / away 10% (no rule — photos are shot from any side)
  //   thumb: acrossPalm 83% / side 17% / up 0% (no rule)
  {
    letter: "Х",
    verified: false,
    fingers: {
      index: { state: "half", hintCode: "finger.round.index" },
      middle: { state: "bent", hintCode: "finger.bend.middle" },
      ring: { state: "bent", hintCode: "finger.bend.ring" },
      pinky: { state: "bent", hintCode: "finger.bend.pinky" },
    },
    reference: "references/Х.json",
    confusedWith: ["Я", "С", "Д"],
  },
  // Ч: 49 samples (kaggle 49), 16 signers, 2 Left/Right fixed, kNN accuracy 90% (leave-one-signer-out)
  //   thumb  straight 98% / half 2% / bent 0%, median 161.5° → rule: straight
  //   index  straight 2% / half 57% / bent 41%, median 101.2° → free
  //   middle straight 0% / half 16% / bent 84%, median 93° → rule: bent
  //   ring   straight 0% / half 0% / bent 100%, median 77.5° → rule: bent
  //   pinky  straight 0% / half 2% / bent 98%, median 78.2° → rule: bent
  //   tips touch: thumb-index 74%, index-middle 63%, ring-pinky 96%
  //   not a rule (both fingers bent): ring-pinky
  //   palm: camera 45% / side 51% / away 4% (no rule — photos are shot from any side)
  //   thumb: acrossPalm 20% / side 78% / up 2% (no rule)
  {
    letter: "Ч",
    verified: false,
    fingers: {
      thumb: { state: "straight", hintCode: "finger.straighten.thumb" },
      middle: { state: "bent", hintCode: "finger.bend.middle" },
      ring: { state: "bent", hintCode: "finger.bend.ring" },
      pinky: { state: "bent", hintCode: "finger.bend.pinky" },
    },
    reference: "references/Ч.json",
  },
  // Ш: 60 samples (kaggle 60), 21 signers, 30 Left/Right fixed, kNN accuracy 85% (leave-one-signer-out)
  //   thumb  straight 37% / half 50% / bent 13%, median 142.2° → free
  //   index  straight 37% / half 63% / bent 0%, median 157.8° → free
  //   middle straight 92% / half 8% / bent 0%, median 169.2° → rule: straight
  //   ring   straight 83% / half 17% / bent 0%, median 165.1° → rule: straight
  //   pinky  straight 7% / half 53% / bent 40%, median 123.9° → free
  //   tips touch: index-middle 52%
  //   palm: camera 0% / side 2% / away 98% (no rule — photos are shot from any side)
  //   thumb: acrossPalm 67% / side 17% / up 17% (no rule)
  {
    letter: "Ш",
    verified: false,
    fingers: {
      middle: { state: "straight", hintCode: "finger.straighten.middle" },
      ring: { state: "straight", hintCode: "finger.straighten.ring" },
    },
    reference: "references/Ш.json",
    confusedWith: ["М"],
  },
  // Ы: 31 samples (kaggle 31), 9 signers, 1 Left/Right fixed, kNN accuracy 100% (leave-one-signer-out)
  //   thumb  straight 0% / half 77% / bent 23%, median 133.4° → free
  //   index  straight 65% / half 36% / bent 0%, median 161.7° → free
  //   middle straight 0% / half 0% / bent 100%, median 63.1° → rule: bent
  //   ring   straight 0% / half 0% / bent 100%, median 57.4° → rule: bent
  //   pinky  straight 48% / half 52% / bent 0%, median 159.8° → free
  //   tips touch: middle-ring 77%
  //   palm: camera 100% / side 0% / away 0% (no rule — photos are shot from any side)
  //   thumb: acrossPalm 94% / side 7% / up 0% (no rule)
  {
    letter: "Ы",
    verified: false,
    fingers: {
      middle: { state: "bent", hintCode: "finger.bend.middle" },
      ring: { state: "bent", hintCode: "finger.bend.ring" },
    },
    reference: "references/Ы.json",
  },
  // Э: 62 samples (kaggle 62), 24 signers, 16 Left/Right fixed, kNN accuracy 92% (leave-one-signer-out)
  //   thumb  straight 89% / half 7% / bent 5%, median 163.3° → rule: straight
  //   index  straight 0% / half 87% / bent 13%, median 137.6° → rule: half
  //   middle straight 0% / half 2% / bent 98%, median 83.4° → rule: bent
  //   ring   straight 0% / half 2% / bent 98%, median 79.1° → rule: bent
  //   pinky  straight 0% / half 11% / bent 89%, median 80.8° → rule: bent
  //   tips touch: middle-ring 86%, ring-pinky 79%
  //   not a rule (both fingers bent): middle-ring
  //   palm: camera 40% / side 52% / away 8% (no rule — photos are shot from any side)
  //   thumb: acrossPalm 24% / side 76% / up 0% (no rule)
  {
    letter: "Э",
    verified: false,
    fingers: {
      thumb: { state: "straight", hintCode: "finger.straighten.thumb" },
      index: { state: "half", hintCode: "finger.round.index" },
      middle: { state: "bent", hintCode: "finger.bend.middle" },
      ring: { state: "bent", hintCode: "finger.bend.ring" },
      pinky: { state: "bent", hintCode: "finger.bend.pinky" },
    },
    reference: "references/Э.json",
    confusedWith: ["Д"],
  },
  // Ю: 49 samples (kaggle 49), 20 signers, 0 Left/Right fixed, kNN accuracy 94% (leave-one-signer-out)
  //   thumb  straight 98% / half 2% / bent 0%, median 159.4° → rule: straight
  //   index  straight 2% / half 98% / bent 0%, median 125.7° → rule: half
  //   middle straight 0% / half 98% / bent 2%, median 118.8° → rule: half
  //   ring   straight 2% / half 96% / bent 2%, median 132.2° → rule: half
  //   pinky  straight 92% / half 8% / bent 0%, median 168.4° → rule: straight
  //   tips touch: index-middle 86%
  //   palm: camera 76% / side 22% / away 2% (no rule — photos are shot from any side)
  //   thumb: acrossPalm 2% / side 90% / up 8% (no rule)
  {
    letter: "Ю",
    verified: false,
    fingers: {
      thumb: { state: "straight", hintCode: "finger.straighten.thumb" },
      index: { state: "half", hintCode: "finger.round.index" },
      middle: { state: "half", hintCode: "finger.round.middle" },
      ring: { state: "half", hintCode: "finger.round.ring" },
      pinky: { state: "straight", hintCode: "finger.straighten.pinky" },
    },
    extra: [{ type: "tipsTouch", a: "index", b: "middle", hintCode: "tips.touch.index-middle" }],
    reference: "references/Ю.json",
  },
  // Я: 56 samples (kaggle 56), 19 signers, 2 Left/Right fixed, kNN accuracy 77% (leave-one-signer-out)
  //   thumb  straight 7% / half 73% / bent 20%, median 129.5° → free
  //   index  straight 5% / half 93% / bent 2%, median 152.5° → rule: half
  //   middle straight 88% / half 7% / bent 5%, median 168° → rule: straight
  //   ring   straight 0% / half 4% / bent 96%, median 64° → rule: bent
  //   pinky  straight 0% / half 14% / bent 86%, median 79.4° → rule: bent
  //   tips touch: index-middle 80%, ring-pinky 86%
  //   not a rule (both fingers bent): ring-pinky
  //   palm: camera 98% / side 2% / away 0% (no rule — photos are shot from any side)
  //   thumb: acrossPalm 88% / side 11% / up 2% (no rule)
  {
    letter: "Я",
    verified: false,
    fingers: {
      index: { state: "half", hintCode: "finger.round.index" },
      middle: { state: "straight", hintCode: "finger.straighten.middle" },
      ring: { state: "bent", hintCode: "finger.bend.ring" },
      pinky: { state: "bent", hintCode: "finger.bend.pinky" },
    },
    extra: [{ type: "tipsTouch", a: "index", b: "middle", hintCode: "tips.touch.index-middle" }],
    reference: "references/Я.json",
    confusedWith: ["К", "Д", "Х"],
  },
];

export const LETTER_BUILD_INFO: Readonly<Record<string, LetterBuildInfo>> = {
  "А": {
    samples: 78,
    sources: { kaggle: 58, rsl: 20 },
    signers: 23,
    flipped: 3,
    accuracy: 0.962,
    mode: "signer",
    freeFingers: ["thumb"],
    impliedTouches: [],
    stats: {
      samples: 78,
      fingers: {
        thumb: { states: { straight: 0.615, half: 0.359, bent: 0.026 }, medianAngle: 155, quartiles: [141.1, 159.1] },
        index: { states: { straight: 0, half: 0.038, bent: 0.962 }, medianAngle: 82, quartiles: [57.9, 89.5] },
        middle: { states: { straight: 0, half: 0.013, bent: 0.987 }, medianAngle: 76.8, quartiles: [51.5, 82] },
        ring: { states: { straight: 0, half: 0.013, bent: 0.987 }, medianAngle: 73.8, quartiles: [41.8, 79.6] },
        pinky: { states: { straight: 0, half: 0.013, bent: 0.987 }, medianAngle: 74.3, quartiles: [35.5, 80.6] },
      },
      tipsTouch: {
        "thumb-index": 0.141,
        "thumb-middle": 0.026,
        "thumb-ring": 0,
        "thumb-pinky": 0,
        "index-middle": 0.667,
        "index-ring": 0.359,
        "index-pinky": 0.321,
        "middle-ring": 0.654,
        "middle-pinky": 0.526,
        "ring-pinky": 0.795,
      },
      palmFacing: { camera: 0.551, side: 0.436, away: 0.013 },
      thumbPosition: { acrossPalm: 0.282, side: 0.436, up: 0.282 },
    },
  },
  "Б": {
    samples: 77,
    sources: { kaggle: 57, rsl: 20 },
    signers: 20,
    flipped: 111,
    accuracy: 0.766,
    mode: "signer",
    freeFingers: ["thumb", "index", "middle"],
    impliedTouches: ["ring-pinky"],
    stats: {
      samples: 77,
      fingers: {
        thumb: { states: { straight: 0.39, half: 0.481, bent: 0.13 }, medianAngle: 143, quartiles: [132.2, 158.2] },
        index: { states: { straight: 0.299, half: 0.649, bent: 0.052 }, medianAngle: 153, quartiles: [132.9, 160.4] },
        middle: {
          states: { straight: 0.052, half: 0.662, bent: 0.286 },
          medianAngle: 107.8,
          quartiles: [98.8, 124.1],
        },
        ring: { states: { straight: 0.013, half: 0.117, bent: 0.87 }, medianAngle: 84.4, quartiles: [79.1, 90.8] },
        pinky: { states: { straight: 0, half: 0.195, bent: 0.805 }, medianAngle: 85.2, quartiles: [79.2, 91.9] },
      },
      tipsTouch: {
        "thumb-index": 0.026,
        "thumb-middle": 0.039,
        "thumb-ring": 0.104,
        "thumb-pinky": 0,
        "index-middle": 0.26,
        "index-ring": 0,
        "index-pinky": 0,
        "middle-ring": 0.078,
        "middle-pinky": 0,
        "ring-pinky": 0.818,
      },
      palmFacing: { camera: 0.182, side: 0.649, away: 0.169 },
      thumbPosition: { acrossPalm: 0.519, side: 0.481, up: 0 },
    },
  },
  "В": {
    samples: 75,
    sources: { kaggle: 55, rsl: 20 },
    signers: 20,
    flipped: 25,
    accuracy: 1,
    mode: "signer",
    freeFingers: ["index"],
    impliedTouches: [],
    stats: {
      samples: 75,
      fingers: {
        thumb: { states: { straight: 1, half: 0, bent: 0 }, medianAngle: 165.6, quartiles: [164, 170.7] },
        index: { states: { straight: 0.733, half: 0.267, bent: 0 }, medianAngle: 161.8, quartiles: [159.7, 162.7] },
        middle: { states: { straight: 1, half: 0, bent: 0 }, medianAngle: 170.3, quartiles: [169.1, 171.3] },
        ring: { states: { straight: 1, half: 0, bent: 0 }, medianAngle: 170.4, quartiles: [169.4, 171.7] },
        pinky: { states: { straight: 0.853, half: 0.147, bent: 0 }, medianAngle: 162.7, quartiles: [161.4, 165.6] },
      },
      tipsTouch: {
        "thumb-index": 0,
        "thumb-middle": 0,
        "thumb-ring": 0,
        "thumb-pinky": 0,
        "index-middle": 0.973,
        "index-ring": 0.027,
        "index-pinky": 0,
        "middle-ring": 0.96,
        "middle-pinky": 0,
        "ring-pinky": 0,
      },
      palmFacing: { camera: 1, side: 0, away: 0 },
      thumbPosition: { acrossPalm: 0, side: 0.987, up: 0.013 },
    },
  },
  "Г": {
    samples: 70,
    sources: { kaggle: 50, rsl: 20 },
    signers: 14,
    flipped: 78,
    accuracy: 0.943,
    mode: "signer",
    freeFingers: [],
    impliedTouches: [],
    stats: {
      samples: 70,
      fingers: {
        thumb: { states: { straight: 0.943, half: 0.057, bent: 0 }, medianAngle: 165.8, quartiles: [161, 173.3] },
        index: { states: { straight: 0, half: 0.971, bent: 0.029 }, medianAngle: 140, quartiles: [125.3, 149.4] },
        middle: { states: { straight: 0, half: 0.014, bent: 0.986 }, medianAngle: 44.7, quartiles: [23.1, 58.3] },
        ring: { states: { straight: 0, half: 0.014, bent: 0.986 }, medianAngle: 48, quartiles: [35.4, 56.8] },
        pinky: { states: { straight: 0, half: 0.014, bent: 0.986 }, medianAngle: 43.7, quartiles: [36.7, 50.2] },
      },
      tipsTouch: {
        "thumb-index": 0,
        "thumb-middle": 0,
        "thumb-ring": 0,
        "thumb-pinky": 0,
        "index-middle": 0.014,
        "index-ring": 0,
        "index-pinky": 0,
        "middle-ring": 0.057,
        "middle-pinky": 0,
        "ring-pinky": 0.586,
      },
      palmFacing: { camera: 0.829, side: 0.171, away: 0 },
      thumbPosition: { acrossPalm: 0, side: 0.814, up: 0.186 },
    },
  },
  "Д": {
    samples: 20,
    sources: { rsl: 20 },
    signers: 1,
    flipped: 22,
    accuracy: 0.6,
    mode: "sample",
    freeFingers: ["thumb", "index", "middle", "ring", "pinky"],
    impliedTouches: [],
    stats: {
      samples: 20,
      fingers: {
        thumb: { states: { straight: 0.55, half: 0.45, bent: 0 }, medianAngle: 152.5, quartiles: [147.3, 161] },
        index: { states: { straight: 0.5, half: 0.5, bent: 0 }, medianAngle: 161, quartiles: [153.3, 167.5] },
        middle: { states: { straight: 0.35, half: 0.5, bent: 0.15 }, medianAngle: 151.9, quartiles: [139.7, 169.7] },
        ring: { states: { straight: 0, half: 0.45, bent: 0.55 }, medianAngle: 91.9, quartiles: [70.7, 138.8] },
        pinky: { states: { straight: 0, half: 0.6, bent: 0.4 }, medianAngle: 109.4, quartiles: [82.1, 132.5] },
      },
      tipsTouch: {
        "thumb-index": 0,
        "thumb-middle": 0.1,
        "thumb-ring": 0.3,
        "thumb-pinky": 0.05,
        "index-middle": 0.35,
        "index-ring": 0,
        "index-pinky": 0,
        "middle-ring": 0,
        "middle-pinky": 0,
        "ring-pinky": 0.45,
      },
      palmFacing: { camera: 0.55, side: 0.45, away: 0 },
      thumbPosition: { acrossPalm: 0.45, side: 0.4, up: 0.15 },
    },
  },
  "Е": {
    samples: 48,
    sources: { kaggle: 48 },
    signers: 10,
    flipped: 2,
    accuracy: 0.938,
    mode: "signer",
    freeFingers: ["index", "middle", "ring"],
    impliedTouches: [],
    stats: {
      samples: 48,
      fingers: {
        thumb: { states: { straight: 0.875, half: 0.125, bent: 0 }, medianAngle: 159.4, quartiles: [155.7, 163.4] },
        index: { states: { straight: 0, half: 0.708, bent: 0.292 }, medianAngle: 108.4, quartiles: [98.9, 114.9] },
        middle: { states: { straight: 0, half: 0.646, bent: 0.354 }, medianAngle: 104.7, quartiles: [95.3, 111.1] },
        ring: { states: { straight: 0, half: 0.583, bent: 0.417 }, medianAngle: 104.7, quartiles: [92.2, 109.8] },
        pinky: { states: { straight: 0, half: 0.875, bent: 0.125 }, medianAngle: 115.4, quartiles: [107.7, 119.3] },
      },
      tipsTouch: {
        "thumb-index": 0.083,
        "thumb-middle": 0.063,
        "thumb-ring": 0.042,
        "thumb-pinky": 0.021,
        "index-middle": 0.896,
        "index-ring": 0.833,
        "index-pinky": 0.542,
        "middle-ring": 0.979,
        "middle-pinky": 0.854,
        "ring-pinky": 0.958,
      },
      palmFacing: { camera: 0.25, side: 0.708, away: 0.042 },
      thumbPosition: { acrossPalm: 0.521, side: 0.458, up: 0.021 },
    },
  },
  "Ё": {
    samples: 20,
    sources: { rsl: 20 },
    signers: 1,
    flipped: 6,
    accuracy: 0.75,
    mode: "sample",
    freeFingers: [],
    impliedTouches: [],
    stats: {
      samples: 20,
      fingers: {
        thumb: { states: { straight: 1, half: 0, bent: 0 }, medianAngle: 166.7, quartiles: [164.5, 170.2] },
        index: { states: { straight: 0.05, half: 0.95, bent: 0 }, medianAngle: 121.6, quartiles: [118.7, 124] },
        middle: { states: { straight: 0, half: 1, bent: 0 }, medianAngle: 114.3, quartiles: [113.3, 118.4] },
        ring: { states: { straight: 0.05, half: 0.9, bent: 0.05 }, medianAngle: 113.4, quartiles: [108.5, 115.1] },
        pinky: { states: { straight: 0, half: 1, bent: 0 }, medianAngle: 111.2, quartiles: [108.2, 116.4] },
      },
      tipsTouch: {
        "thumb-index": 0.4,
        "thumb-middle": 0.2,
        "thumb-ring": 0.05,
        "thumb-pinky": 0.05,
        "index-middle": 0.85,
        "index-ring": 0.15,
        "index-pinky": 0,
        "middle-ring": 0.8,
        "middle-pinky": 0.05,
        "ring-pinky": 1,
      },
      palmFacing: { camera: 0.15, side: 0.8, away: 0.05 },
      thumbPosition: { acrossPalm: 0, side: 1, up: 0 },
    },
  },
  "Ж": {
    samples: 71,
    sources: { kaggle: 51, rsl: 20 },
    signers: 21,
    flipped: 80,
    accuracy: 0.789,
    mode: "signer",
    freeFingers: ["index", "middle", "ring", "pinky"],
    impliedTouches: [],
    stats: {
      samples: 71,
      fingers: {
        thumb: {
          states: { straight: 0.944, half: 0.042, bent: 0.014 },
          medianAngle: 162.9,
          quartiles: [159.6, 166.7],
        },
        index: {
          states: { straight: 0.014, half: 0.563, bent: 0.423 },
          medianAngle: 101.9,
          quartiles: [93.3, 113.2],
        },
        middle: { states: { straight: 0.014, half: 0.366, bent: 0.62 }, medianAngle: 96, quartiles: [88.2, 107] },
        ring: { states: { straight: 0.028, half: 0.324, bent: 0.648 }, medianAngle: 96.4, quartiles: [88.6, 102.7] },
        pinky: { states: { straight: 0.028, half: 0.408, bent: 0.563 }, medianAngle: 98, quartiles: [89.9, 108.8] },
      },
      tipsTouch: {
        "thumb-index": 0.282,
        "thumb-middle": 0.239,
        "thumb-ring": 0.197,
        "thumb-pinky": 0.324,
        "index-middle": 0.817,
        "index-ring": 0.577,
        "index-pinky": 0.394,
        "middle-ring": 0.761,
        "middle-pinky": 0.254,
        "ring-pinky": 0.859,
      },
      palmFacing: { camera: 0.183, side: 0.38, away: 0.437 },
      thumbPosition: { acrossPalm: 0.296, side: 0.676, up: 0.028 },
    },
  },
  "З": {
    samples: 20,
    sources: { rsl: 20 },
    signers: 1,
    flipped: 0,
    accuracy: 1,
    mode: "sample",
    freeFingers: ["middle"],
    impliedTouches: ["ring-pinky"],
    stats: {
      samples: 20,
      fingers: {
        thumb: { states: { straight: 0.05, half: 0.95, bent: 0 }, medianAngle: 141.6, quartiles: [133.7, 143.5] },
        index: { states: { straight: 0.95, half: 0.05, bent: 0 }, medianAngle: 168.7, quartiles: [167.3, 169.4] },
        middle: { states: { straight: 0.15, half: 0.4, bent: 0.45 }, medianAngle: 107.3, quartiles: [94.5, 120] },
        ring: { states: { straight: 0, half: 0.1, bent: 0.9 }, medianAngle: 87.4, quartiles: [82, 92.7] },
        pinky: { states: { straight: 0, half: 0.05, bent: 0.95 }, medianAngle: 88.4, quartiles: [85.2, 91.8] },
      },
      tipsTouch: {
        "thumb-index": 0,
        "thumb-middle": 0.25,
        "thumb-ring": 0.2,
        "thumb-pinky": 0,
        "index-middle": 0.1,
        "index-ring": 0,
        "index-pinky": 0,
        "middle-ring": 0.1,
        "middle-pinky": 0,
        "ring-pinky": 0.95,
      },
      palmFacing: { camera: 1, side: 0, away: 0 },
      thumbPosition: { acrossPalm: 1, side: 0, up: 0 },
    },
  },
  "И": {
    samples: 56,
    sources: { kaggle: 56 },
    signers: 16,
    flipped: 0,
    accuracy: 0.857,
    mode: "signer",
    freeFingers: ["thumb", "ring", "pinky"],
    impliedTouches: [],
    stats: {
      samples: 56,
      fingers: {
        thumb: {
          states: { straight: 0.107, half: 0.536, bent: 0.357 },
          medianAngle: 126.5,
          quartiles: [111.7, 138.1],
        },
        index: { states: { straight: 0.054, half: 0.125, bent: 0.821 }, medianAngle: 69.3, quartiles: [61, 85.5] },
        middle: { states: { straight: 0, half: 0.089, bent: 0.911 }, medianAngle: 73.3, quartiles: [65.5, 81.3] },
        ring: {
          states: { straight: 0.107, half: 0.679, bent: 0.214 },
          medianAngle: 153.6,
          quartiles: [143.1, 156.8],
        },
        pinky: { states: { straight: 0.786, half: 0.196, bent: 0.018 }, medianAngle: 170, quartiles: [165.3, 171.5] },
      },
      tipsTouch: {
        "thumb-index": 0.214,
        "thumb-middle": 0.107,
        "thumb-ring": 0,
        "thumb-pinky": 0,
        "index-middle": 0.518,
        "index-ring": 0.054,
        "index-pinky": 0,
        "middle-ring": 0.071,
        "middle-pinky": 0,
        "ring-pinky": 0,
      },
      palmFacing: { camera: 1, side: 0, away: 0 },
      thumbPosition: { acrossPalm: 0.054, side: 0.946, up: 0 },
    },
  },
  "Й": {
    samples: 20,
    sources: { rsl: 20 },
    signers: 1,
    flipped: 0,
    accuracy: 1,
    mode: "sample",
    freeFingers: [],
    impliedTouches: ["index-middle"],
    stats: {
      samples: 20,
      fingers: {
        thumb: { states: { straight: 0.2, half: 0.8, bent: 0 }, medianAngle: 147.2, quartiles: [143.2, 149] },
        index: { states: { straight: 0, half: 0, bent: 1 }, medianAngle: 49, quartiles: [47.5, 50.3] },
        middle: { states: { straight: 0, half: 0, bent: 1 }, medianAngle: 49.8, quartiles: [48.6, 52.2] },
        ring: { states: { straight: 1, half: 0, bent: 0 }, medianAngle: 166.5, quartiles: [165.6, 167.2] },
        pinky: { states: { straight: 1, half: 0, bent: 0 }, medianAngle: 163.1, quartiles: [162.1, 164.2] },
      },
      tipsTouch: {
        "thumb-index": 0.05,
        "thumb-middle": 0.9,
        "thumb-ring": 0,
        "thumb-pinky": 0,
        "index-middle": 0.9,
        "index-ring": 0,
        "index-pinky": 0,
        "middle-ring": 0,
        "middle-pinky": 0,
        "ring-pinky": 0.5,
      },
      palmFacing: { camera: 1, side: 0, away: 0 },
      thumbPosition: { acrossPalm: 0.85, side: 0.15, up: 0 },
    },
  },
  "К": {
    samples: 76,
    sources: { kaggle: 56, rsl: 20 },
    signers: 17,
    flipped: 86,
    accuracy: 0.671,
    mode: "signer",
    freeFingers: ["thumb", "index", "middle"],
    impliedTouches: ["ring-pinky"],
    stats: {
      samples: 76,
      fingers: {
        thumb: {
          states: { straight: 0.224, half: 0.487, bent: 0.289 },
          medianAngle: 133.3,
          quartiles: [118.7, 149.4],
        },
        index: { states: { straight: 0.579, half: 0.421, bent: 0 }, medianAngle: 162.2, quartiles: [157.2, 166.8] },
        middle: { states: { straight: 0.289, half: 0.658, bent: 0.053 }, medianAngle: 152.9, quartiles: [146, 160.7] },
        ring: { states: { straight: 0.013, half: 0.026, bent: 0.961 }, medianAngle: 79.3, quartiles: [74.9, 84.3] },
        pinky: { states: { straight: 0, half: 0.066, bent: 0.934 }, medianAngle: 80.4, quartiles: [75.9, 86.7] },
      },
      tipsTouch: {
        "thumb-index": 0,
        "thumb-middle": 0.013,
        "thumb-ring": 0.395,
        "thumb-pinky": 0.026,
        "index-middle": 0.25,
        "index-ring": 0.013,
        "index-pinky": 0,
        "middle-ring": 0.039,
        "middle-pinky": 0.026,
        "ring-pinky": 0.803,
      },
      palmFacing: { camera: 0.447, side: 0.434, away: 0.118 },
      thumbPosition: { acrossPalm: 0.684, side: 0.316, up: 0 },
    },
  },
  "Л": {
    samples: 75,
    sources: { kaggle: 55, rsl: 20 },
    signers: 24,
    flipped: 5,
    accuracy: 0.867,
    mode: "signer",
    freeFingers: ["thumb", "index", "middle"],
    impliedTouches: [],
    stats: {
      samples: 75,
      fingers: {
        thumb: { states: { straight: 0.307, half: 0.693, bent: 0 }, medianAngle: 146.3, quartiles: [140.8, 150.7] },
        index: { states: { straight: 0.44, half: 0.56, bent: 0 }, medianAngle: 155.8, quartiles: [143.3, 167.1] },
        middle: { states: { straight: 0.453, half: 0.547, bent: 0 }, medianAngle: 155.8, quartiles: [140.2, 169.9] },
        ring: { states: { straight: 0, half: 0.093, bent: 0.907 }, medianAngle: 56.5, quartiles: [29.3, 71.6] },
        pinky: { states: { straight: 0, half: 0.16, bent: 0.84 }, medianAngle: 78.4, quartiles: [50.1, 90] },
      },
      tipsTouch: {
        "thumb-index": 0,
        "thumb-middle": 0,
        "thumb-ring": 0.32,
        "thumb-pinky": 0.013,
        "index-middle": 0.013,
        "index-ring": 0,
        "index-pinky": 0,
        "middle-ring": 0,
        "middle-pinky": 0,
        "ring-pinky": 0.493,
      },
      palmFacing: { camera: 0, side: 0.147, away: 0.853 },
      thumbPosition: { acrossPalm: 0.653, side: 0.32, up: 0.027 },
    },
  },
  "М": {
    samples: 69,
    sources: { kaggle: 49, rsl: 20 },
    signers: 20,
    flipped: 1,
    accuracy: 0.725,
    mode: "signer",
    freeFingers: ["thumb", "index", "middle", "ring", "pinky"],
    impliedTouches: [],
    stats: {
      samples: 69,
      fingers: {
        thumb: { states: { straight: 0.725, half: 0.275, bent: 0 }, medianAngle: 152.2, quartiles: [149.1, 156.5] },
        index: { states: { straight: 0.449, half: 0.551, bent: 0 }, medianAngle: 156.7, quartiles: [145.2, 168.2] },
        middle: { states: { straight: 0.464, half: 0.536, bent: 0 }, medianAngle: 158.8, quartiles: [146, 174.6] },
        ring: { states: { straight: 0.449, half: 0.536, bent: 0.014 }, medianAngle: 156.9, quartiles: [143, 174.4] },
        pinky: { states: { straight: 0.188, half: 0.739, bent: 0.072 }, medianAngle: 135.4, quartiles: [123, 156.3] },
      },
      tipsTouch: {
        "thumb-index": 0,
        "thumb-middle": 0,
        "thumb-ring": 0,
        "thumb-pinky": 0,
        "index-middle": 0,
        "index-ring": 0,
        "index-pinky": 0,
        "middle-ring": 0.014,
        "middle-pinky": 0,
        "ring-pinky": 0,
      },
      palmFacing: { camera: 0, side: 0.13, away: 0.87 },
      thumbPosition: { acrossPalm: 0.174, side: 0.696, up: 0.13 },
    },
  },
  "Н": {
    samples: 80,
    sources: { kaggle: 60, rsl: 20 },
    signers: 20,
    flipped: 1,
    accuracy: 0.988,
    mode: "signer",
    freeFingers: ["thumb"],
    impliedTouches: [],
    stats: {
      samples: 80,
      fingers: {
        thumb: {
          states: { straight: 0.013, half: 0.65, bent: 0.338 },
          medianAngle: 127.5,
          quartiles: [117.2, 132.2],
        },
        index: { states: { straight: 0.938, half: 0.063, bent: 0 }, medianAngle: 172.3, quartiles: [168.4, 173.6] },
        middle: { states: { straight: 0.975, half: 0.025, bent: 0 }, medianAngle: 166.9, quartiles: [162.6, 170.2] },
        ring: { states: { straight: 0.013, half: 0, bent: 0.988 }, medianAngle: 70.7, quartiles: [55.8, 78.1] },
        pinky: { states: { straight: 0.95, half: 0.05, bent: 0 }, medianAngle: 165.8, quartiles: [163.1, 167.8] },
      },
      tipsTouch: {
        "thumb-index": 0.013,
        "thumb-middle": 0,
        "thumb-ring": 0.388,
        "thumb-pinky": 0,
        "index-middle": 0.013,
        "index-ring": 0,
        "index-pinky": 0,
        "middle-ring": 0,
        "middle-pinky": 0,
        "ring-pinky": 0,
      },
      palmFacing: { camera: 0.988, side: 0.013, away: 0 },
      thumbPosition: { acrossPalm: 0.938, side: 0.063, up: 0 },
    },
  },
  "О": {
    samples: 80,
    sources: { kaggle: 60, rsl: 20 },
    signers: 23,
    flipped: 107,
    accuracy: 0.663,
    mode: "signer",
    freeFingers: ["middle", "ring", "pinky"],
    impliedTouches: [],
    stats: {
      samples: 80,
      fingers: {
        thumb: { states: { straight: 0.888, half: 0.1, bent: 0.013 }, medianAngle: 160.3, quartiles: [154.8, 165.8] },
        index: { states: { straight: 0.113, half: 0.85, bent: 0.038 }, medianAngle: 122, quartiles: [113.1, 139.7] },
        middle: { states: { straight: 0.238, half: 0.763, bent: 0 }, medianAngle: 153.4, quartiles: [144, 159.3] },
        ring: { states: { straight: 0.375, half: 0.625, bent: 0 }, medianAngle: 155, quartiles: [144.5, 165.2] },
        pinky: {
          states: { straight: 0.35, half: 0.638, bent: 0.013 },
          medianAngle: 156.2,
          quartiles: [150.1, 164.6],
        },
      },
      tipsTouch: {
        "thumb-index": 0.313,
        "thumb-middle": 0,
        "thumb-ring": 0.013,
        "thumb-pinky": 0,
        "index-middle": 0.1,
        "index-ring": 0.038,
        "index-pinky": 0.013,
        "middle-ring": 0.063,
        "middle-pinky": 0,
        "ring-pinky": 0.038,
      },
      palmFacing: { camera: 0.163, side: 0.15, away: 0.688 },
      thumbPosition: { acrossPalm: 0.038, side: 0.913, up: 0.05 },
    },
  },
  "П": {
    samples: 68,
    sources: { kaggle: 48, rsl: 20 },
    signers: 19,
    flipped: 33,
    accuracy: 0.426,
    mode: "signer",
    freeFingers: ["thumb", "index", "middle", "ring", "pinky"],
    impliedTouches: [],
    stats: {
      samples: 68,
      fingers: {
        thumb: { states: { straight: 0.632, half: 0.368, bent: 0 }, medianAngle: 154.2, quartiles: [145.2, 163.9] },
        index: {
          states: { straight: 0.279, half: 0.603, bent: 0.118 },
          medianAngle: 128.5,
          quartiles: [110.3, 160.6],
        },
        middle: {
          states: { straight: 0.162, half: 0.559, bent: 0.279 },
          medianAngle: 126.1,
          quartiles: [98.3, 152.7],
        },
        ring: { states: { straight: 0.059, half: 0.206, bent: 0.735 }, medianAngle: 72.4, quartiles: [47.1, 100.7] },
        pinky: { states: { straight: 0.074, half: 0.265, bent: 0.662 }, medianAngle: 87.2, quartiles: [61.1, 109.1] },
      },
      tipsTouch: {
        "thumb-index": 0,
        "thumb-middle": 0.029,
        "thumb-ring": 0.015,
        "thumb-pinky": 0,
        "index-middle": 0.338,
        "index-ring": 0.029,
        "index-pinky": 0.015,
        "middle-ring": 0.044,
        "middle-pinky": 0.029,
        "ring-pinky": 0.426,
      },
      palmFacing: { camera: 0.015, side: 0.588, away: 0.397 },
      thumbPosition: { acrossPalm: 0.265, side: 0.456, up: 0.279 },
    },
  },
  "Р": {
    samples: 74,
    sources: { kaggle: 54, rsl: 20 },
    signers: 18,
    flipped: 2,
    accuracy: 0.865,
    mode: "signer",
    freeFingers: ["thumb", "index", "middle", "ring"],
    impliedTouches: [],
    stats: {
      samples: 74,
      fingers: {
        thumb: {
          states: { straight: 0.635, half: 0.351, bent: 0.014 },
          medianAngle: 154.6,
          quartiles: [144.9, 159.5],
        },
        index: {
          states: { straight: 0.743, half: 0.216, bent: 0.041 },
          medianAngle: 164.2,
          quartiles: [159.7, 166.8],
        },
        middle: { states: { straight: 0.068, half: 0.378, bent: 0.554 }, medianAngle: 94.6, quartiles: [63.1, 108] },
        ring: {
          states: { straight: 0.716, half: 0.23, bent: 0.054 },
          medianAngle: 164.5,
          quartiles: [158.8, 168.5],
        },
        pinky: { states: { straight: 0.838, half: 0.162, bent: 0 }, medianAngle: 167.2, quartiles: [162.1, 170] },
      },
      tipsTouch: {
        "thumb-index": 0.041,
        "thumb-middle": 0.365,
        "thumb-ring": 0.041,
        "thumb-pinky": 0,
        "index-middle": 0.014,
        "index-ring": 0,
        "index-pinky": 0,
        "middle-ring": 0.014,
        "middle-pinky": 0,
        "ring-pinky": 0,
      },
      palmFacing: { camera: 0.892, side: 0.108, away: 0 },
      thumbPosition: { acrossPalm: 0.027, side: 0.973, up: 0 },
    },
  },
  "С": {
    samples: 77,
    sources: { kaggle: 57, rsl: 20 },
    signers: 22,
    flipped: 127,
    accuracy: 0.74,
    mode: "signer",
    freeFingers: [],
    impliedTouches: [],
    stats: {
      samples: 77,
      fingers: {
        thumb: { states: { straight: 0.896, half: 0.104, bent: 0 }, medianAngle: 160.1, quartiles: [155, 164.2] },
        index: { states: { straight: 0.013, half: 0.961, bent: 0.026 }, medianAngle: 136.6, quartiles: [127.9, 142] },
        middle: { states: { straight: 0, half: 0.935, bent: 0.065 }, medianAngle: 131.4, quartiles: [121.6, 135.7] },
        ring: { states: { straight: 0, half: 0.922, bent: 0.078 }, medianAngle: 131.2, quartiles: [120.5, 137.5] },
        pinky: { states: { straight: 0, half: 0.935, bent: 0.065 }, medianAngle: 141.5, quartiles: [134.5, 145.9] },
      },
      tipsTouch: {
        "thumb-index": 0.065,
        "thumb-middle": 0.039,
        "thumb-ring": 0,
        "thumb-pinky": 0,
        "index-middle": 0.649,
        "index-ring": 0.519,
        "index-pinky": 0.091,
        "middle-ring": 0.766,
        "middle-pinky": 0.091,
        "ring-pinky": 0.571,
      },
      palmFacing: { camera: 0.078, side: 0.636, away: 0.286 },
      thumbPosition: { acrossPalm: 0.273, side: 0.701, up: 0.026 },
    },
  },
  "Т": {
    samples: 71,
    sources: { kaggle: 51, rsl: 20 },
    signers: 19,
    flipped: 93,
    accuracy: 0.592,
    mode: "signer",
    freeFingers: ["thumb", "ring"],
    impliedTouches: [],
    stats: {
      samples: 71,
      fingers: {
        thumb: { states: { straight: 0.69, half: 0.31, bent: 0 }, medianAngle: 153.3, quartiles: [148.3, 162.5] },
        index: { states: { straight: 0.141, half: 0.817, bent: 0.042 }, medianAngle: 133.1, quartiles: [124.4, 153] },
        middle: { states: { straight: 0.141, half: 0.803, bent: 0.056 }, medianAngle: 134.8, quartiles: [121, 154.3] },
        ring: {
          states: { straight: 0.141, half: 0.761, bent: 0.099 },
          medianAngle: 134.1,
          quartiles: [116.8, 146.7],
        },
        pinky: { states: { straight: 0.085, half: 0.803, bent: 0.113 }, medianAngle: 130, quartiles: [117, 138.4] },
      },
      tipsTouch: {
        "thumb-index": 0.028,
        "thumb-middle": 0.056,
        "thumb-ring": 0.028,
        "thumb-pinky": 0.014,
        "index-middle": 0.352,
        "index-ring": 0.07,
        "index-pinky": 0,
        "middle-ring": 0.254,
        "middle-pinky": 0,
        "ring-pinky": 0.028,
      },
      palmFacing: { camera: 0.366, side: 0.521, away: 0.113 },
      thumbPosition: { acrossPalm: 0.169, side: 0.465, up: 0.366 },
    },
  },
  "У": {
    samples: 80,
    sources: { kaggle: 60, rsl: 20 },
    signers: 22,
    flipped: 0,
    accuracy: 0.963,
    mode: "signer",
    freeFingers: [],
    impliedTouches: [],
    stats: {
      samples: 80,
      fingers: {
        thumb: { states: { straight: 0.963, half: 0.038, bent: 0 }, medianAngle: 169.6, quartiles: [164.8, 171.1] },
        index: { states: { straight: 0, half: 0.025, bent: 0.975 }, medianAngle: 60.8, quartiles: [43.7, 72.8] },
        middle: { states: { straight: 0, half: 0.025, bent: 0.975 }, medianAngle: 63.9, quartiles: [44.8, 72.8] },
        ring: { states: { straight: 0, half: 0, bent: 1 }, medianAngle: 56.1, quartiles: [31.5, 68.5] },
        pinky: {
          states: { straight: 0.85, half: 0.113, bent: 0.038 },
          medianAngle: 167.9,
          quartiles: [162.5, 170.4],
        },
      },
      tipsTouch: {
        "thumb-index": 0,
        "thumb-middle": 0,
        "thumb-ring": 0,
        "thumb-pinky": 0,
        "index-middle": 0.775,
        "index-ring": 0,
        "index-pinky": 0,
        "middle-ring": 0.738,
        "middle-pinky": 0,
        "ring-pinky": 0.025,
      },
      palmFacing: { camera: 1, side: 0, away: 0 },
      thumbPosition: { acrossPalm: 0, side: 0.663, up: 0.338 },
    },
  },
  "Ф": {
    samples: 69,
    sources: { kaggle: 49, rsl: 20 },
    signers: 19,
    flipped: 63,
    accuracy: 0.638,
    mode: "signer",
    freeFingers: ["index", "middle", "ring", "pinky"],
    impliedTouches: [],
    stats: {
      samples: 69,
      fingers: {
        thumb: { states: { straight: 0.971, half: 0.029, bent: 0 }, medianAngle: 168.5, quartiles: [165.2, 171] },
        index: { states: { straight: 0.058, half: 0.333, bent: 0.609 }, medianAngle: 92.5, quartiles: [87.2, 136.5] },
        middle: { states: { straight: 0.116, half: 0.232, bent: 0.652 }, medianAngle: 89.3, quartiles: [80.5, 124.8] },
        ring: { states: { straight: 0.101, half: 0.261, bent: 0.638 }, medianAngle: 92.4, quartiles: [80.7, 127.2] },
        pinky: { states: { straight: 0.116, half: 0.449, bent: 0.435 }, medianAngle: 103.5, quartiles: [90.4, 142] },
      },
      tipsTouch: {
        "thumb-index": 0.014,
        "thumb-middle": 0.029,
        "thumb-ring": 0,
        "thumb-pinky": 0,
        "index-middle": 0.71,
        "index-ring": 0.478,
        "index-pinky": 0.232,
        "middle-ring": 0.739,
        "middle-pinky": 0.304,
        "ring-pinky": 0.507,
      },
      palmFacing: { camera: 0.203, side: 0.667, away: 0.13 },
      thumbPosition: { acrossPalm: 0.072, side: 0.812, up: 0.116 },
    },
  },
  "Х": {
    samples: 83,
    sources: { kaggle: 63, rsl: 20 },
    signers: 23,
    flipped: 94,
    accuracy: 0.711,
    mode: "signer",
    freeFingers: ["thumb"],
    impliedTouches: ["middle-ring", "ring-pinky"],
    stats: {
      samples: 83,
      fingers: {
        thumb: { states: { straight: 0.458, half: 0.482, bent: 0.06 }, medianAngle: 149, quartiles: [140.7, 155.5] },
        index: { states: { straight: 0, half: 0.952, bent: 0.048 }, medianAngle: 138.9, quartiles: [130.2, 144] },
        middle: { states: { straight: 0, half: 0.012, bent: 0.988 }, medianAngle: 84.8, quartiles: [67.5, 88.3] },
        ring: { states: { straight: 0, half: 0, bent: 1 }, medianAngle: 80, quartiles: [66.6, 82.6] },
        pinky: { states: { straight: 0.012, half: 0.048, bent: 0.94 }, medianAngle: 79.7, quartiles: [65.6, 85.6] },
      },
      tipsTouch: {
        "thumb-index": 0.012,
        "thumb-middle": 0.048,
        "thumb-ring": 0,
        "thumb-pinky": 0,
        "index-middle": 0.036,
        "index-ring": 0,
        "index-pinky": 0,
        "middle-ring": 0.904,
        "middle-pinky": 0.157,
        "ring-pinky": 0.916,
      },
      palmFacing: { camera: 0.313, side: 0.59, away: 0.096 },
      thumbPosition: { acrossPalm: 0.831, side: 0.169, up: 0 },
    },
  },
  "Ч": {
    samples: 49,
    sources: { kaggle: 49 },
    signers: 16,
    flipped: 2,
    accuracy: 0.898,
    mode: "signer",
    freeFingers: ["index"],
    impliedTouches: ["ring-pinky"],
    stats: {
      samples: 49,
      fingers: {
        thumb: { states: { straight: 0.98, half: 0.02, bent: 0 }, medianAngle: 161.5, quartiles: [156.2, 166.1] },
        index: { states: { straight: 0.02, half: 0.571, bent: 0.408 }, medianAngle: 101.2, quartiles: [96.6, 106.6] },
        middle: { states: { straight: 0, half: 0.163, bent: 0.837 }, medianAngle: 93, quartiles: [88.8, 97.8] },
        ring: { states: { straight: 0, half: 0, bent: 1 }, medianAngle: 77.5, quartiles: [75.1, 81.7] },
        pinky: { states: { straight: 0, half: 0.02, bent: 0.98 }, medianAngle: 78.2, quartiles: [75.3, 80.9] },
      },
      tipsTouch: {
        "thumb-index": 0.735,
        "thumb-middle": 0.469,
        "thumb-ring": 0,
        "thumb-pinky": 0,
        "index-middle": 0.633,
        "index-ring": 0.02,
        "index-pinky": 0,
        "middle-ring": 0.061,
        "middle-pinky": 0.061,
        "ring-pinky": 0.959,
      },
      palmFacing: { camera: 0.449, side: 0.51, away: 0.041 },
      thumbPosition: { acrossPalm: 0.204, side: 0.776, up: 0.02 },
    },
  },
  "Ш": {
    samples: 60,
    sources: { kaggle: 60 },
    signers: 21,
    flipped: 30,
    accuracy: 0.85,
    mode: "signer",
    freeFingers: ["thumb", "index", "pinky"],
    impliedTouches: [],
    stats: {
      samples: 60,
      fingers: {
        thumb: { states: { straight: 0.367, half: 0.5, bent: 0.133 }, medianAngle: 142.2, quartiles: [126.2, 153.3] },
        index: { states: { straight: 0.367, half: 0.633, bent: 0 }, medianAngle: 157.8, quartiles: [150.9, 162.6] },
        middle: { states: { straight: 0.917, half: 0.083, bent: 0 }, medianAngle: 169.2, quartiles: [165.5, 171.8] },
        ring: { states: { straight: 0.833, half: 0.167, bent: 0 }, medianAngle: 165.1, quartiles: [161.9, 170.8] },
        pinky: { states: { straight: 0.067, half: 0.533, bent: 0.4 }, medianAngle: 123.9, quartiles: [78.1, 140] },
      },
      tipsTouch: {
        "thumb-index": 0,
        "thumb-middle": 0,
        "thumb-ring": 0,
        "thumb-pinky": 0.183,
        "index-middle": 0.517,
        "index-ring": 0,
        "index-pinky": 0,
        "middle-ring": 0.283,
        "middle-pinky": 0,
        "ring-pinky": 0,
      },
      palmFacing: { camera: 0, side: 0.017, away: 0.983 },
      thumbPosition: { acrossPalm: 0.667, side: 0.167, up: 0.167 },
    },
  },
  "Ы": {
    samples: 31,
    sources: { kaggle: 31 },
    signers: 9,
    flipped: 1,
    accuracy: 1,
    mode: "signer",
    freeFingers: ["thumb", "index", "pinky"],
    impliedTouches: [],
    stats: {
      samples: 31,
      fingers: {
        thumb: { states: { straight: 0, half: 0.774, bent: 0.226 }, medianAngle: 133.4, quartiles: [120.8, 137.4] },
        index: { states: { straight: 0.645, half: 0.355, bent: 0 }, medianAngle: 161.7, quartiles: [159.1, 168.5] },
        middle: { states: { straight: 0, half: 0, bent: 1 }, medianAngle: 63.1, quartiles: [52.6, 69.5] },
        ring: { states: { straight: 0, half: 0, bent: 1 }, medianAngle: 57.4, quartiles: [47.4, 64.2] },
        pinky: { states: { straight: 0.484, half: 0.516, bent: 0 }, medianAngle: 159.8, quartiles: [156.3, 164.6] },
      },
      tipsTouch: {
        "thumb-index": 0,
        "thumb-middle": 0.161,
        "thumb-ring": 0.226,
        "thumb-pinky": 0,
        "index-middle": 0,
        "index-ring": 0,
        "index-pinky": 0,
        "middle-ring": 0.774,
        "middle-pinky": 0,
        "ring-pinky": 0,
      },
      palmFacing: { camera: 1, side: 0, away: 0 },
      thumbPosition: { acrossPalm: 0.935, side: 0.065, up: 0 },
    },
  },
  "Э": {
    samples: 62,
    sources: { kaggle: 62 },
    signers: 24,
    flipped: 16,
    accuracy: 0.919,
    mode: "signer",
    freeFingers: [],
    impliedTouches: ["middle-ring"],
    stats: {
      samples: 62,
      fingers: {
        thumb: {
          states: { straight: 0.887, half: 0.065, bent: 0.048 },
          medianAngle: 163.3,
          quartiles: [159.5, 166.5],
        },
        index: { states: { straight: 0, half: 0.871, bent: 0.129 }, medianAngle: 137.6, quartiles: [124.6, 142.8] },
        middle: { states: { straight: 0, half: 0.016, bent: 0.984 }, medianAngle: 83.4, quartiles: [77.7, 86.8] },
        ring: { states: { straight: 0, half: 0.016, bent: 0.984 }, medianAngle: 79.1, quartiles: [72.1, 82.6] },
        pinky: { states: { straight: 0, half: 0.113, bent: 0.887 }, medianAngle: 80.8, quartiles: [72.1, 87.6] },
      },
      tipsTouch: {
        "thumb-index": 0.016,
        "thumb-middle": 0.048,
        "thumb-ring": 0.016,
        "thumb-pinky": 0.016,
        "index-middle": 0.016,
        "index-ring": 0.016,
        "index-pinky": 0.016,
        "middle-ring": 0.855,
        "middle-pinky": 0.29,
        "ring-pinky": 0.79,
      },
      palmFacing: { camera: 0.403, side: 0.516, away: 0.081 },
      thumbPosition: { acrossPalm: 0.242, side: 0.758, up: 0 },
    },
  },
  "Ю": {
    samples: 49,
    sources: { kaggle: 49 },
    signers: 20,
    flipped: 0,
    accuracy: 0.939,
    mode: "signer",
    freeFingers: [],
    impliedTouches: [],
    stats: {
      samples: 49,
      fingers: {
        thumb: { states: { straight: 0.98, half: 0.02, bent: 0 }, medianAngle: 159.4, quartiles: [156.6, 163.2] },
        index: { states: { straight: 0.02, half: 0.98, bent: 0 }, medianAngle: 125.7, quartiles: [116, 131.8] },
        middle: { states: { straight: 0, half: 0.98, bent: 0.02 }, medianAngle: 118.8, quartiles: [113.7, 125.1] },
        ring: { states: { straight: 0.02, half: 0.959, bent: 0.02 }, medianAngle: 132.2, quartiles: [124.8, 146.8] },
        pinky: { states: { straight: 0.918, half: 0.082, bent: 0 }, medianAngle: 168.4, quartiles: [166.5, 171.8] },
      },
      tipsTouch: {
        "thumb-index": 0.429,
        "thumb-middle": 0.061,
        "thumb-ring": 0.02,
        "thumb-pinky": 0,
        "index-middle": 0.857,
        "index-ring": 0.204,
        "index-pinky": 0,
        "middle-ring": 0.469,
        "middle-pinky": 0,
        "ring-pinky": 0.02,
      },
      palmFacing: { camera: 0.755, side: 0.224, away: 0.02 },
      thumbPosition: { acrossPalm: 0.02, side: 0.898, up: 0.082 },
    },
  },
  "Я": {
    samples: 56,
    sources: { kaggle: 56 },
    signers: 19,
    flipped: 2,
    accuracy: 0.768,
    mode: "signer",
    freeFingers: ["thumb"],
    impliedTouches: ["ring-pinky"],
    stats: {
      samples: 56,
      fingers: {
        thumb: {
          states: { straight: 0.071, half: 0.732, bent: 0.196 },
          medianAngle: 129.5,
          quartiles: [121.7, 136.5],
        },
        index: {
          states: { straight: 0.054, half: 0.929, bent: 0.018 },
          medianAngle: 152.5,
          quartiles: [149.7, 155.4],
        },
        middle: { states: { straight: 0.875, half: 0.071, bent: 0.054 }, medianAngle: 168, quartiles: [163.3, 171] },
        ring: { states: { straight: 0, half: 0.036, bent: 0.964 }, medianAngle: 64, quartiles: [49.8, 70.5] },
        pinky: { states: { straight: 0, half: 0.143, bent: 0.857 }, medianAngle: 79.4, quartiles: [62.2, 89.6] },
      },
      tipsTouch: {
        "thumb-index": 0.018,
        "thumb-middle": 0.054,
        "thumb-ring": 0.161,
        "thumb-pinky": 0.018,
        "index-middle": 0.804,
        "index-ring": 0,
        "index-pinky": 0,
        "middle-ring": 0.018,
        "middle-pinky": 0,
        "ring-pinky": 0.857,
      },
      palmFacing: { camera: 0.982, side: 0.018, away: 0 },
      thumbPosition: { acrossPalm: 0.875, side: 0.107, up: 0.018 },
    },
  },
};
